### ISSUE TITLE
Issue deploying on Windows 10

### ISSUE THREAD

**Issue by m0ngr31** [jimjkelly/lambda-deploy#1]
Trying to get this going on Windows, but running into an error:

```
2016-04-18 11:38:33:INFO:botocore.credentials: Found credentials in environment variables.
2016-04-18 11:38:33:INFO:lambda_deploy: Packaging lambda .env
Traceback (most recent call last):
  File "C:\Users\Joe\appdata\local\scoop\apps\python27\2.7.10\scripts\lambda-deploy-script.py", line 9, in <module>
    load_entry_point('lambda-deploy==0.0.1', 'console_scripts', 'lambda-deploy')()
  File "C:\Users\Joe\appdata\local\scoop\apps\python27\2.7.10\lib\site-packages\lambda_deploy\lambda_deploy.py", line 321, in main
    method()
  File "C:\Users\Joe\appdata\local\scoop\apps\python27\2.7.10\lib\site-packages\lambda_deploy\lambda_deploy.py", line 133, in deploy
    zfh = self.package(lambda_name)
  File "C:\Users\Joe\appdata\local\scoop\apps\python27\2.7.10\lib\site-packages\lambda_deploy\lambda_deploy.py", line 98, in package
    if 'requirements.txt' in os.listdir(src_dir):
WindowsError: [Error 267] The directory name is invalid: 'C:\\Dev\\python\\kodi-alexa-master\\.env/*.*'
```

This is my .env file: 

``` AWS_DEFAULT_REGION=us-east-1
AWS_ACCESS_KEY_ID=***********
AWS_SECRET_ACCESS_KEY=*****************
LAMBDA_ROLE=lambda_basic_execution
LAMBDA_TIMEOUT=30
```

It looks like it's trying to use `.env` as a directory that everything is in. Anything I can try?

**Comment by jimjkelly** [comment]
Hmm, definitely a bug.  Two work around while I work on a fix:

One, put your lambda or lambdas in a separate directory and point the tool at that:

```
current_directory
  |- .env
  |- lambdas
      |- your_lambda_dir
```

Then in current_directory, run lambda_deploy like so:

```
$ lambda-deploy -d lambdas deploy
```

The other option, especially if you only have one to upload, is to specify the lambda:

```
$ lambda-deploy deploy your_lambda_dir
```

**Comment by jimjkelly** [comment]
Also - I'm definitely interested to hear about your experiences on Windows - I haven't tested this there at all so I'd like to hear if it works.

**Comment by m0ngr31** [comment]
Yeah, I tried that after I wrote the issue and it seemed to work.

Once I figured out how to use yaep to use the environment variables, this turned into a pretty great way to deploy to lambda, glad I found the project! Now I can't wait to get a version where I can have it in the same directory.

**Comment by jimjkelly** [comment]
Should be a `0.0.2` version up now - let me know if this fixes the problem, thanks!

**Comment by m0ngr31** [comment]
It seems to fix the issue, but it just stops what it's doing:

```
$ lambda-deploy deploy
2016-04-18 14:32:21:INFO:botocore.credentials: Found credentials in environment variables.
```

Doesn't upgrade or anything.

**Comment by jimjkelly** [comment]
So you have a layout like:

```
current_directory (where you run lambda-deploy from)
  | - .env
  | - your_lambda_directory
```

?

Or are you trying to upload from inside "your_lambda_directory"?

**Comment by m0ngr31** [comment]
Trying to do it inside of the lambda directory if that's possible

**Comment by jimjkelly** [comment]
Hmm. I'll have to give some though to that, I guess I didn't really think much about uploading individual Lambdas. I have a stable of them that I keep in a repo with the idea that the tool can run on a CI machine to deploy them on commit (obviously blindly just updating them all, but no big deal).

I guess I could have the "search" logic to find lambda folders only operate if you give the -d argument to specify a directory, and otherwise assume there's a single lambda in the current directory.

That'll probably take some time though. I'll look into it.
