### ISSUE TITLE
Have Default Action be Single Upload of the Current Directory

### ISSUE THREAD

**Issue by jimjkelly** [jimjkelly/lambda-deploy#2]
As requested in issue #1, it might make more sense that the default deploy action is to deploy the current directory as a single Lambda, and only search for multiple Lambdas if the `-d` option is given. Some things to consider:
- We'll want to filter out .env files then, since we don't want to by default upload their credentials
- Is there any value in confirming that the entry point as specified exists? Probably. That could be good in either case.

**Comment by m0ngr31** [comment]
I made a PR, for the most basic of handling this. I'll need to dig in a bit more and see about the other stuff.

**Comment by jimjkelly** [comment]
I created PR #4 to address some of the issues that we discussed - I'm going to play with it a bit over the next day or two but it seems to work correctly.  Feel free to give it a gander and test it out and if you have any issues/ideas feel free to let me know. I'l merge it in a couple days if I don't find anything.

**Comment by jimjkelly** [comment]
Resolved by #4
